var baseLayer = new ol.layer.Group({
    'title': 'Base maps',
    layers: [
new ol.layer.Tile({
    'title': 'Stamen Watercolor',
    'type': 'base',
    source: new ol.source.Stamen({
        layer: 'watercolor'
    })
})
]
});
var format_France = new ol.format.GeoJSON();
var features_France = format_France.readFeatures(geojson_France, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_France = new ol.source.Vector();
jsonSource_France.addFeatures(features_France);var lyr_France = new ol.layer.Vector({
                source:jsonSource_France, 
                style: style_France,
                title: "France"
            });var format_IledeFrance = new ol.format.GeoJSON();
var features_IledeFrance = format_IledeFrance.readFeatures(geojson_IledeFrance, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_IledeFrance = new ol.source.Vector();
jsonSource_IledeFrance.addFeatures(features_IledeFrance);var lyr_IledeFrance = new ol.layer.Vector({
                source:jsonSource_IledeFrance, 
                style: style_IledeFrance,
                title: "Ile-de-France"
            });var format_GrandOuest = new ol.format.GeoJSON();
var features_GrandOuest = format_GrandOuest.readFeatures(geojson_GrandOuest, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_GrandOuest = new ol.source.Vector();
jsonSource_GrandOuest.addFeatures(features_GrandOuest);var lyr_GrandOuest = new ol.layer.Vector({
                source:jsonSource_GrandOuest, 
                style: style_GrandOuest,
                title: "Grand Ouest"
            });var format_AireUrbainedeRennes = new ol.format.GeoJSON();
var features_AireUrbainedeRennes = format_AireUrbainedeRennes.readFeatures(geojson_AireUrbainedeRennes, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_AireUrbainedeRennes = new ol.source.Vector();
jsonSource_AireUrbainedeRennes.addFeatures(features_AireUrbainedeRennes);var lyr_AireUrbainedeRennes = new ol.layer.Vector({
                source:jsonSource_AireUrbainedeRennes, 
                style: style_AireUrbainedeRennes,
                title: "Aire Urbaine de Rennes"
            });var format_RennesMetropoleEstOuest = new ol.format.GeoJSON();
var features_RennesMetropoleEstOuest = format_RennesMetropoleEstOuest.readFeatures(geojson_RennesMetropoleEstOuest, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_RennesMetropoleEstOuest = new ol.source.Vector();
jsonSource_RennesMetropoleEstOuest.addFeatures(features_RennesMetropoleEstOuest);var lyr_RennesMetropoleEstOuest = new ol.layer.Vector({
                source:jsonSource_RennesMetropoleEstOuest, 
                style: style_RennesMetropoleEstOuest,
                title: "Rennes Metropole Est-Ouest"
            });var format_RennesMetropoleNordSud = new ol.format.GeoJSON();
var features_RennesMetropoleNordSud = format_RennesMetropoleNordSud.readFeatures(geojson_RennesMetropoleNordSud, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_RennesMetropoleNordSud = new ol.source.Vector();
jsonSource_RennesMetropoleNordSud.addFeatures(features_RennesMetropoleNordSud);var lyr_RennesMetropoleNordSud = new ol.layer.Vector({
                source:jsonSource_RennesMetropoleNordSud, 
                style: style_RennesMetropoleNordSud,
                title: "Rennes Metropole Nord-Sud"
            });var format_RennesMtropole = new ol.format.GeoJSON();
var features_RennesMtropole = format_RennesMtropole.readFeatures(geojson_RennesMtropole, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_RennesMtropole = new ol.source.Vector();
jsonSource_RennesMtropole.addFeatures(features_RennesMtropole);var lyr_RennesMtropole = new ol.layer.Vector({
                source:jsonSource_RennesMtropole, 
                style: style_RennesMtropole,
                title: "Rennes Métropole"
            });var format_CoeurdeMetropole = new ol.format.GeoJSON();
var features_CoeurdeMetropole = format_CoeurdeMetropole.readFeatures(geojson_CoeurdeMetropole, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_CoeurdeMetropole = new ol.source.Vector();
jsonSource_CoeurdeMetropole.addFeatures(features_CoeurdeMetropole);var lyr_CoeurdeMetropole = new ol.layer.Vector({
                source:jsonSource_CoeurdeMetropole, 
                style: style_CoeurdeMetropole,
                title: "Coeur de Metropole"
            });var format_Coeur1 = new ol.format.GeoJSON();
var features_Coeur1 = format_Coeur1.readFeatures(geojson_Coeur1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Coeur1 = new ol.source.Vector();
jsonSource_Coeur1.addFeatures(features_Coeur1);var lyr_Coeur1 = new ol.layer.Vector({
                source:jsonSource_Coeur1, 
                style: style_Coeur1,
                title: "Coeur1"
            });var format_Coeur2 = new ol.format.GeoJSON();
var features_Coeur2 = format_Coeur2.readFeatures(geojson_Coeur2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Coeur2 = new ol.source.Vector();
jsonSource_Coeur2.addFeatures(features_Coeur2);var lyr_Coeur2 = new ol.layer.Vector({
                source:jsonSource_Coeur2, 
                style: style_Coeur2,
                title: "Coeur2"
            });var format_Rennes = new ol.format.GeoJSON();
var features_Rennes = format_Rennes.readFeatures(geojson_Rennes, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Rennes = new ol.source.Vector();
jsonSource_Rennes.addFeatures(features_Rennes);var lyr_Rennes = new ol.layer.Vector({
                source:jsonSource_Rennes, 
                style: style_Rennes,
                title: "Rennes"
            });var format_Polestructurant = new ol.format.GeoJSON();
var features_Polestructurant = format_Polestructurant.readFeatures(geojson_Polestructurant, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Polestructurant = new ol.source.Vector();
jsonSource_Polestructurant.addFeatures(features_Polestructurant);var lyr_Polestructurant = new ol.layer.Vector({
                source:jsonSource_Polestructurant, 
                style: style_Polestructurant,
                title: "Pole structurant"
            });

lyr_France.setVisible(true);lyr_IledeFrance.setVisible(true);lyr_GrandOuest.setVisible(true);lyr_AireUrbainedeRennes.setVisible(true);lyr_RennesMetropoleEstOuest.setVisible(true);lyr_RennesMetropoleNordSud.setVisible(true);lyr_RennesMtropole.setVisible(true);lyr_CoeurdeMetropole.setVisible(true);lyr_Coeur1.setVisible(true);lyr_Coeur2.setVisible(true);lyr_Rennes.setVisible(true);lyr_Polestructurant.setVisible(true);
var layersList = [baseLayer,lyr_France,lyr_IledeFrance,lyr_GrandOuest,lyr_AireUrbainedeRennes,lyr_RennesMetropoleEstOuest,lyr_RennesMetropoleNordSud,lyr_RennesMtropole,lyr_CoeurdeMetropole,lyr_Coeur1,lyr_Coeur2,lyr_Rennes,lyr_Polestructurant];
lyr_France.set('fieldAliases', {'code_insee': 'code_insee', 'nom': 'nom', 'nuts3': 'nuts3', 'wikipedia': 'wikipedia', 'wikidata': 'wikidata', 'surf_ha': 'surf_ha', });
lyr_IledeFrance.set('fieldAliases', {'code_insee': 'code_insee', 'nom': 'nom', 'nuts3': 'nuts3', 'wikipedia': 'wikipedia', 'wikidata': 'wikidata', 'surf_ha': 'surf_ha', });
lyr_GrandOuest.set('fieldAliases', {'code_insee': 'code_insee', 'nom': 'nom', 'nuts3': 'nuts3', 'wikipedia': 'wikipedia', 'wikidata': 'wikidata', 'surf_ha': 'surf_ha', });
lyr_AireUrbainedeRennes.set('fieldAliases', {'ID_GEOFLA': 'ID_GEOFLA', 'CODE_COM': 'CODE_COM', 'INSEE_COM': 'INSEE_COM', 'NOM_COM': 'NOM_COM', 'STATUT': 'STATUT', 'X_CHF_LIEU': 'X_CHF_LIEU', 'Y_CHF_LIEU': 'Y_CHF_LIEU', 'X_CENTROID': 'X_CENTROID', 'Y_CENTROID': 'Y_CENTROID', 'Z_MOYEN': 'Z_MOYEN', 'SUPERFICIE': 'SUPERFICIE', 'POPULATION': 'POPULATION', 'CODE_ARR': 'CODE_ARR', 'CODE_DEPT': 'CODE_DEPT', 'NOM_DEPT': 'NOM_DEPT', 'CODE_REG': 'CODE_REG', 'NOM_REG': 'NOM_REG', 'MED': 'MED', 'AU': 'AU', '2015 any_Field2': '2015 any_Field2', '2015 any_Field3': '2015 any_Field3', '2015 any_Field4': '2015 any_Field4', '2015 any_Field5': '2015 any_Field5', '2015 any_Field6': '2015 any_Field6', '2015 any_Field7': '2015 any_Field7', '2015 any_Field8': '2015 any_Field8', '2015 any_Field9': '2015 any_Field9', '2015 any_Field10': '2015 any_Field10', '2015 any_Field11': '2015 any_Field11', '2015 any_Field12': '2015 any_Field12', '2015 any_Field13': '2015 any_Field13', '2015 any_Field14': '2015 any_Field14', '2015 any_Field15': '2015 any_Field15', '2015 any_Field16': '2015 any_Field16', '2015 any_Field17': '2015 any_Field17', });
lyr_RennesMetropoleEstOuest.set('fieldAliases', {'ID_GEOFLA': 'ID_GEOFLA', 'CODE_COM': 'CODE_COM', 'INSEE_COM': 'INSEE_COM', 'NOM_COM': 'NOM_COM', 'STATUT': 'STATUT', 'X_CHF_LIEU': 'X_CHF_LIEU', 'Y_CHF_LIEU': 'Y_CHF_LIEU', 'X_CENTROID': 'X_CENTROID', 'Y_CENTROID': 'Y_CENTROID', 'Z_MOYEN': 'Z_MOYEN', 'SUPERFICIE': 'SUPERFICIE', 'POPULATION': 'POPULATION', 'CODE_ARR': 'CODE_ARR', 'CODE_DEPT': 'CODE_DEPT', 'NOM_DEPT': 'NOM_DEPT', 'CODE_REG': 'CODE_REG', 'NOM_REG': 'NOM_REG', 'MED': 'MED', '2015 any_Field2': '2015 any_Field2', '2015 any_Field3': '2015 any_Field3', '2015 any_Field4': '2015 any_Field4', '2015 any_Field5': '2015 any_Field5', '2015 any_Field6': '2015 any_Field6', '2015 any_Field7': '2015 any_Field7', '2015 any_Field8': '2015 any_Field8', '2015 any_Field9': '2015 any_Field9', '2015 any_Field10': '2015 any_Field10', '2015 any_Field11': '2015 any_Field11', '2015 any_Field12': '2015 any_Field12', '2015 any_Field13': '2015 any_Field13', '2015 any_Field14': '2015 any_Field14', '2015 any_Field15': '2015 any_Field15', '2015 any_Field16': '2015 any_Field16', '2015 any_Field17': '2015 any_Field17', });
lyr_RennesMetropoleNordSud.set('fieldAliases', {'ID_GEOFLA': 'ID_GEOFLA', 'CODE_COM': 'CODE_COM', 'INSEE_COM': 'INSEE_COM', 'NOM_COM': 'NOM_COM', 'STATUT': 'STATUT', 'X_CHF_LIEU': 'X_CHF_LIEU', 'Y_CHF_LIEU': 'Y_CHF_LIEU', 'X_CENTROID': 'X_CENTROID', 'Y_CENTROID': 'Y_CENTROID', 'Z_MOYEN': 'Z_MOYEN', 'SUPERFICIE': 'SUPERFICIE', 'POPULATION': 'POPULATION', 'CODE_ARR': 'CODE_ARR', 'CODE_DEPT': 'CODE_DEPT', 'NOM_DEPT': 'NOM_DEPT', 'CODE_REG': 'CODE_REG', 'NOM_REG': 'NOM_REG', 'MED': 'MED', '2015 any_Field2': '2015 any_Field2', '2015 any_Field3': '2015 any_Field3', '2015 any_Field4': '2015 any_Field4', '2015 any_Field5': '2015 any_Field5', '2015 any_Field6': '2015 any_Field6', '2015 any_Field7': '2015 any_Field7', '2015 any_Field8': '2015 any_Field8', '2015 any_Field9': '2015 any_Field9', '2015 any_Field10': '2015 any_Field10', '2015 any_Field11': '2015 any_Field11', '2015 any_Field12': '2015 any_Field12', '2015 any_Field13': '2015 any_Field13', '2015 any_Field14': '2015 any_Field14', '2015 any_Field15': '2015 any_Field15', '2015 any_Field16': '2015 any_Field16', '2015 any_Field17': '2015 any_Field17', });
lyr_RennesMtropole.set('fieldAliases', {'siren_epci': 'siren_epci', 'nom_epci': 'nom_epci', 'ptot_epci': 'ptot_epci', 'surf_km2': 'surf_km2', 'short_name': 'short_name', 'wikipedia': 'wikipedia', 'web': 'web', 'osm_id': 'osm_id', 'nom_osm': 'nom_osm', 'type_epci': 'type_epci', '2015 any_Field1': '2015 any_Field1', '2015 any_Field2': '2015 any_Field2', '2015 any_Field3': '2015 any_Field3', '2015 any_Field4': '2015 any_Field4', '2015 any_Field5': '2015 any_Field5', '2015 any_Field7': '2015 any_Field7', '2015 any_Field8': '2015 any_Field8', '2015 any_Field9': '2015 any_Field9', '2015 any_Field10': '2015 any_Field10', '2015 any_Field11': '2015 any_Field11', '2015 any_Field12': '2015 any_Field12', '2015 any_Field13': '2015 any_Field13', '2015 any_Field14': '2015 any_Field14', '2015 any_Field15': '2015 any_Field15', '2015 any_Field16': '2015 any_Field16', '2015 any_Field17': '2015 any_Field17', });
lyr_CoeurdeMetropole.set('fieldAliases', {'ID_GEOFLA': 'ID_GEOFLA', 'CODE_COM': 'CODE_COM', 'INSEE_COM': 'INSEE_COM', 'NOM_COM': 'NOM_COM', 'STATUT': 'STATUT', 'X_CHF_LIEU': 'X_CHF_LIEU', 'Y_CHF_LIEU': 'Y_CHF_LIEU', 'X_CENTROID': 'X_CENTROID', 'Y_CENTROID': 'Y_CENTROID', 'Z_MOYEN': 'Z_MOYEN', 'SUPERFICIE': 'SUPERFICIE', 'POPULATION': 'POPULATION', 'CODE_ARR': 'CODE_ARR', 'CODE_DEPT': 'CODE_DEPT', 'NOM_DEPT': 'NOM_DEPT', 'CODE_REG': 'CODE_REG', 'NOM_REG': 'NOM_REG', 'MED': 'MED', '2015 any_Field2': '2015 any_Field2', '2015 any_Field3': '2015 any_Field3', '2015 any_Field4': '2015 any_Field4', '2015 any_Field5': '2015 any_Field5', '2015 any_Field6': '2015 any_Field6', '2015 any_Field7': '2015 any_Field7', '2015 any_Field8': '2015 any_Field8', '2015 any_Field9': '2015 any_Field9', '2015 any_Field10': '2015 any_Field10', '2015 any_Field11': '2015 any_Field11', '2015 any_Field12': '2015 any_Field12', '2015 any_Field13': '2015 any_Field13', '2015 any_Field14': '2015 any_Field14', '2015 any_Field15': '2015 any_Field15', '2015 any_Field16': '2015 any_Field16', '2015 any_Field17': '2015 any_Field17', });
lyr_Coeur1.set('fieldAliases', {'ID_GEOFLA': 'ID_GEOFLA', 'CODE_COM': 'CODE_COM', 'INSEE_COM': 'INSEE_COM', 'NOM_COM': 'NOM_COM', 'STATUT': 'STATUT', 'X_CHF_LIEU': 'X_CHF_LIEU', 'Y_CHF_LIEU': 'Y_CHF_LIEU', 'X_CENTROID': 'X_CENTROID', 'Y_CENTROID': 'Y_CENTROID', 'Z_MOYEN': 'Z_MOYEN', 'SUPERFICIE': 'SUPERFICIE', 'POPULATION': 'POPULATION', 'CODE_ARR': 'CODE_ARR', 'CODE_DEPT': 'CODE_DEPT', 'NOM_DEPT': 'NOM_DEPT', 'CODE_REG': 'CODE_REG', 'NOM_REG': 'NOM_REG', 'MED': 'MED', '2015 any_Field2': '2015 any_Field2', '2015 any_Field3': '2015 any_Field3', '2015 any_Field4': '2015 any_Field4', '2015 any_Field5': '2015 any_Field5', '2015 any_Field6': '2015 any_Field6', '2015 any_Field7': '2015 any_Field7', '2015 any_Field8': '2015 any_Field8', '2015 any_Field9': '2015 any_Field9', '2015 any_Field10': '2015 any_Field10', '2015 any_Field11': '2015 any_Field11', '2015 any_Field12': '2015 any_Field12', '2015 any_Field13': '2015 any_Field13', '2015 any_Field14': '2015 any_Field14', '2015 any_Field15': '2015 any_Field15', '2015 any_Field16': '2015 any_Field16', '2015 any_Field17': '2015 any_Field17', });
lyr_Coeur2.set('fieldAliases', {'ID_GEOFLA': 'ID_GEOFLA', 'CODE_COM': 'CODE_COM', 'INSEE_COM': 'INSEE_COM', 'NOM_COM': 'NOM_COM', 'STATUT': 'STATUT', 'X_CHF_LIEU': 'X_CHF_LIEU', 'Y_CHF_LIEU': 'Y_CHF_LIEU', 'X_CENTROID': 'X_CENTROID', 'Y_CENTROID': 'Y_CENTROID', 'Z_MOYEN': 'Z_MOYEN', 'SUPERFICIE': 'SUPERFICIE', 'POPULATION': 'POPULATION', 'CODE_ARR': 'CODE_ARR', 'CODE_DEPT': 'CODE_DEPT', 'NOM_DEPT': 'NOM_DEPT', 'CODE_REG': 'CODE_REG', 'NOM_REG': 'NOM_REG', 'MED': 'MED', '2015 any_Field2': '2015 any_Field2', '2015 any_Field3': '2015 any_Field3', '2015 any_Field4': '2015 any_Field4', '2015 any_Field5': '2015 any_Field5', '2015 any_Field6': '2015 any_Field6', '2015 any_Field7': '2015 any_Field7', '2015 any_Field8': '2015 any_Field8', '2015 any_Field9': '2015 any_Field9', '2015 any_Field10': '2015 any_Field10', '2015 any_Field11': '2015 any_Field11', '2015 any_Field12': '2015 any_Field12', '2015 any_Field13': '2015 any_Field13', '2015 any_Field14': '2015 any_Field14', '2015 any_Field15': '2015 any_Field15', '2015 any_Field16': '2015 any_Field16', '2015 any_Field17': '2015 any_Field17', });
lyr_Rennes.set('fieldAliases', {'ID_GEOFLA': 'ID_GEOFLA', 'CODE_COM': 'CODE_COM', 'INSEE_COM': 'INSEE_COM', 'NOM_COM': 'NOM_COM', 'STATUT': 'STATUT', 'X_CHF_LIEU': 'X_CHF_LIEU', 'Y_CHF_LIEU': 'Y_CHF_LIEU', 'X_CENTROID': 'X_CENTROID', 'Y_CENTROID': 'Y_CENTROID', 'Z_MOYEN': 'Z_MOYEN', 'SUPERFICIE': 'SUPERFICIE', 'POPULATION': 'POPULATION', 'CODE_ARR': 'CODE_ARR', 'CODE_DEPT': 'CODE_DEPT', 'NOM_DEPT': 'NOM_DEPT', 'CODE_REG': 'CODE_REG', 'NOM_REG': 'NOM_REG', 'MED': 'MED', '2015 any_Field2': '2015 any_Field2', '2015 any_Field3': '2015 any_Field3', '2015 any_Field4': '2015 any_Field4', '2015 any_Field5': '2015 any_Field5', '2015 any_Field6': '2015 any_Field6', '2015 any_Field7': '2015 any_Field7', '2015 any_Field8': '2015 any_Field8', '2015 any_Field9': '2015 any_Field9', '2015 any_Field10': '2015 any_Field10', '2015 any_Field11': '2015 any_Field11', '2015 any_Field12': '2015 any_Field12', '2015 any_Field13': '2015 any_Field13', '2015 any_Field14': '2015 any_Field14', '2015 any_Field15': '2015 any_Field15', '2015 any_Field16': '2015 any_Field16', '2015 any_Field17': '2015 any_Field17', });
lyr_Polestructurant.set('fieldAliases', {'ID_GEOFLA': 'ID_GEOFLA', 'CODE_COM': 'CODE_COM', 'INSEE_COM': 'INSEE_COM', 'NOM_COM': 'NOM_COM', 'STATUT': 'STATUT', 'X_CHF_LIEU': 'X_CHF_LIEU', 'Y_CHF_LIEU': 'Y_CHF_LIEU', 'X_CENTROID': 'X_CENTROID', 'Y_CENTROID': 'Y_CENTROID', 'Z_MOYEN': 'Z_MOYEN', 'SUPERFICIE': 'SUPERFICIE', 'POPULATION': 'POPULATION', 'CODE_ARR': 'CODE_ARR', 'CODE_DEPT': 'CODE_DEPT', 'NOM_DEPT': 'NOM_DEPT', 'CODE_REG': 'CODE_REG', 'NOM_REG': 'NOM_REG', 'MED': 'MED', '2015 any_Field2': '2015 any_Field2', '2015 any_Field3': '2015 any_Field3', '2015 any_Field4': '2015 any_Field4', '2015 any_Field5': '2015 any_Field5', '2015 any_Field6': '2015 any_Field6', '2015 any_Field7': '2015 any_Field7', '2015 any_Field8': '2015 any_Field8', '2015 any_Field9': '2015 any_Field9', '2015 any_Field10': '2015 any_Field10', '2015 any_Field11': '2015 any_Field11', '2015 any_Field12': '2015 any_Field12', '2015 any_Field13': '2015 any_Field13', '2015 any_Field14': '2015 any_Field14', '2015 any_Field15': '2015 any_Field15', '2015 any_Field16': '2015 any_Field16', '2015 any_Field17': '2015 any_Field17', });
lyr_France.set('fieldImages', {'code_insee': 'TextEdit', 'nom': 'TextEdit', 'nuts3': 'TextEdit', 'wikipedia': 'TextEdit', 'wikidata': 'TextEdit', 'surf_ha': 'TextEdit', });
lyr_IledeFrance.set('fieldImages', {'code_insee': 'TextEdit', 'nom': 'TextEdit', 'nuts3': 'TextEdit', 'wikipedia': 'TextEdit', 'wikidata': 'TextEdit', 'surf_ha': 'TextEdit', });
lyr_GrandOuest.set('fieldImages', {'code_insee': 'TextEdit', 'nom': 'TextEdit', 'nuts3': 'TextEdit', 'wikipedia': 'TextEdit', 'wikidata': 'TextEdit', 'surf_ha': 'TextEdit', });
lyr_AireUrbainedeRennes.set('fieldImages', {'ID_GEOFLA': 'TextEdit', 'CODE_COM': 'TextEdit', 'INSEE_COM': 'TextEdit', 'NOM_COM': 'TextEdit', 'STATUT': 'TextEdit', 'X_CHF_LIEU': 'TextEdit', 'Y_CHF_LIEU': 'TextEdit', 'X_CENTROID': 'TextEdit', 'Y_CENTROID': 'TextEdit', 'Z_MOYEN': 'TextEdit', 'SUPERFICIE': 'TextEdit', 'POPULATION': 'TextEdit', 'CODE_ARR': 'TextEdit', 'CODE_DEPT': 'TextEdit', 'NOM_DEPT': 'TextEdit', 'CODE_REG': 'TextEdit', 'NOM_REG': 'TextEdit', 'MED': 'TextEdit', 'AU': 'TextEdit', '2015 any_Field2': 'TextEdit', '2015 any_Field3': 'TextEdit', '2015 any_Field4': 'TextEdit', '2015 any_Field5': 'TextEdit', '2015 any_Field6': 'TextEdit', '2015 any_Field7': 'TextEdit', '2015 any_Field8': 'TextEdit', '2015 any_Field9': 'TextEdit', '2015 any_Field10': 'TextEdit', '2015 any_Field11': 'TextEdit', '2015 any_Field12': 'TextEdit', '2015 any_Field13': 'TextEdit', '2015 any_Field14': 'TextEdit', '2015 any_Field15': 'TextEdit', '2015 any_Field16': 'TextEdit', '2015 any_Field17': 'TextEdit', });
lyr_RennesMetropoleEstOuest.set('fieldImages', {'ID_GEOFLA': 'TextEdit', 'CODE_COM': 'TextEdit', 'INSEE_COM': 'TextEdit', 'NOM_COM': 'TextEdit', 'STATUT': 'TextEdit', 'X_CHF_LIEU': 'TextEdit', 'Y_CHF_LIEU': 'TextEdit', 'X_CENTROID': 'TextEdit', 'Y_CENTROID': 'TextEdit', 'Z_MOYEN': 'TextEdit', 'SUPERFICIE': 'TextEdit', 'POPULATION': 'TextEdit', 'CODE_ARR': 'TextEdit', 'CODE_DEPT': 'TextEdit', 'NOM_DEPT': 'TextEdit', 'CODE_REG': 'TextEdit', 'NOM_REG': 'TextEdit', 'MED': 'TextEdit', '2015 any_Field2': 'TextEdit', '2015 any_Field3': 'TextEdit', '2015 any_Field4': 'TextEdit', '2015 any_Field5': 'TextEdit', '2015 any_Field6': 'TextEdit', '2015 any_Field7': 'TextEdit', '2015 any_Field8': 'TextEdit', '2015 any_Field9': 'TextEdit', '2015 any_Field10': 'TextEdit', '2015 any_Field11': 'TextEdit', '2015 any_Field12': 'TextEdit', '2015 any_Field13': 'TextEdit', '2015 any_Field14': 'TextEdit', '2015 any_Field15': 'TextEdit', '2015 any_Field16': 'TextEdit', '2015 any_Field17': 'TextEdit', });
lyr_RennesMetropoleNordSud.set('fieldImages', {'ID_GEOFLA': 'TextEdit', 'CODE_COM': 'TextEdit', 'INSEE_COM': 'TextEdit', 'NOM_COM': 'TextEdit', 'STATUT': 'TextEdit', 'X_CHF_LIEU': 'TextEdit', 'Y_CHF_LIEU': 'TextEdit', 'X_CENTROID': 'TextEdit', 'Y_CENTROID': 'TextEdit', 'Z_MOYEN': 'TextEdit', 'SUPERFICIE': 'TextEdit', 'POPULATION': 'TextEdit', 'CODE_ARR': 'TextEdit', 'CODE_DEPT': 'TextEdit', 'NOM_DEPT': 'TextEdit', 'CODE_REG': 'TextEdit', 'NOM_REG': 'TextEdit', 'MED': 'TextEdit', '2015 any_Field2': 'TextEdit', '2015 any_Field3': 'TextEdit', '2015 any_Field4': 'TextEdit', '2015 any_Field5': 'TextEdit', '2015 any_Field6': 'TextEdit', '2015 any_Field7': 'TextEdit', '2015 any_Field8': 'TextEdit', '2015 any_Field9': 'TextEdit', '2015 any_Field10': 'TextEdit', '2015 any_Field11': 'TextEdit', '2015 any_Field12': 'TextEdit', '2015 any_Field13': 'TextEdit', '2015 any_Field14': 'TextEdit', '2015 any_Field15': 'TextEdit', '2015 any_Field16': 'TextEdit', '2015 any_Field17': 'TextEdit', });
lyr_RennesMtropole.set('fieldImages', {'siren_epci': 'TextEdit', 'nom_epci': 'TextEdit', 'ptot_epci': 'TextEdit', 'surf_km2': 'TextEdit', 'short_name': 'TextEdit', 'wikipedia': 'TextEdit', 'web': 'TextEdit', 'osm_id': 'TextEdit', 'nom_osm': 'TextEdit', 'type_epci': 'TextEdit', '2015 any_Field1': 'TextEdit', '2015 any_Field2': 'TextEdit', '2015 any_Field3': 'TextEdit', '2015 any_Field4': 'TextEdit', '2015 any_Field5': 'TextEdit', '2015 any_Field7': 'TextEdit', '2015 any_Field8': 'TextEdit', '2015 any_Field9': 'TextEdit', '2015 any_Field10': 'TextEdit', '2015 any_Field11': 'TextEdit', '2015 any_Field12': 'TextEdit', '2015 any_Field13': 'TextEdit', '2015 any_Field14': 'TextEdit', '2015 any_Field15': 'TextEdit', '2015 any_Field16': 'TextEdit', '2015 any_Field17': 'TextEdit', });
lyr_CoeurdeMetropole.set('fieldImages', {'ID_GEOFLA': 'TextEdit', 'CODE_COM': 'TextEdit', 'INSEE_COM': 'TextEdit', 'NOM_COM': 'TextEdit', 'STATUT': 'TextEdit', 'X_CHF_LIEU': 'TextEdit', 'Y_CHF_LIEU': 'TextEdit', 'X_CENTROID': 'TextEdit', 'Y_CENTROID': 'TextEdit', 'Z_MOYEN': 'TextEdit', 'SUPERFICIE': 'TextEdit', 'POPULATION': 'TextEdit', 'CODE_ARR': 'TextEdit', 'CODE_DEPT': 'TextEdit', 'NOM_DEPT': 'TextEdit', 'CODE_REG': 'TextEdit', 'NOM_REG': 'TextEdit', 'MED': 'TextEdit', '2015 any_Field2': 'TextEdit', '2015 any_Field3': 'TextEdit', '2015 any_Field4': 'TextEdit', '2015 any_Field5': 'TextEdit', '2015 any_Field6': 'TextEdit', '2015 any_Field7': 'TextEdit', '2015 any_Field8': 'TextEdit', '2015 any_Field9': 'TextEdit', '2015 any_Field10': 'TextEdit', '2015 any_Field11': 'TextEdit', '2015 any_Field12': 'TextEdit', '2015 any_Field13': 'TextEdit', '2015 any_Field14': 'TextEdit', '2015 any_Field15': 'TextEdit', '2015 any_Field16': 'TextEdit', '2015 any_Field17': 'TextEdit', });
lyr_Coeur1.set('fieldImages', {'ID_GEOFLA': 'TextEdit', 'CODE_COM': 'TextEdit', 'INSEE_COM': 'TextEdit', 'NOM_COM': 'TextEdit', 'STATUT': 'TextEdit', 'X_CHF_LIEU': 'TextEdit', 'Y_CHF_LIEU': 'TextEdit', 'X_CENTROID': 'TextEdit', 'Y_CENTROID': 'TextEdit', 'Z_MOYEN': 'TextEdit', 'SUPERFICIE': 'TextEdit', 'POPULATION': 'TextEdit', 'CODE_ARR': 'TextEdit', 'CODE_DEPT': 'TextEdit', 'NOM_DEPT': 'TextEdit', 'CODE_REG': 'TextEdit', 'NOM_REG': 'TextEdit', 'MED': 'TextEdit', '2015 any_Field2': 'TextEdit', '2015 any_Field3': 'TextEdit', '2015 any_Field4': 'TextEdit', '2015 any_Field5': 'TextEdit', '2015 any_Field6': 'TextEdit', '2015 any_Field7': 'TextEdit', '2015 any_Field8': 'TextEdit', '2015 any_Field9': 'TextEdit', '2015 any_Field10': 'TextEdit', '2015 any_Field11': 'TextEdit', '2015 any_Field12': 'TextEdit', '2015 any_Field13': 'TextEdit', '2015 any_Field14': 'TextEdit', '2015 any_Field15': 'TextEdit', '2015 any_Field16': 'TextEdit', '2015 any_Field17': 'TextEdit', });
lyr_Coeur2.set('fieldImages', {'ID_GEOFLA': 'TextEdit', 'CODE_COM': 'TextEdit', 'INSEE_COM': 'TextEdit', 'NOM_COM': 'TextEdit', 'STATUT': 'TextEdit', 'X_CHF_LIEU': 'TextEdit', 'Y_CHF_LIEU': 'TextEdit', 'X_CENTROID': 'TextEdit', 'Y_CENTROID': 'TextEdit', 'Z_MOYEN': 'TextEdit', 'SUPERFICIE': 'TextEdit', 'POPULATION': 'TextEdit', 'CODE_ARR': 'TextEdit', 'CODE_DEPT': 'TextEdit', 'NOM_DEPT': 'TextEdit', 'CODE_REG': 'TextEdit', 'NOM_REG': 'TextEdit', 'MED': 'TextEdit', '2015 any_Field2': 'TextEdit', '2015 any_Field3': 'TextEdit', '2015 any_Field4': 'TextEdit', '2015 any_Field5': 'TextEdit', '2015 any_Field6': 'TextEdit', '2015 any_Field7': 'TextEdit', '2015 any_Field8': 'TextEdit', '2015 any_Field9': 'TextEdit', '2015 any_Field10': 'TextEdit', '2015 any_Field11': 'TextEdit', '2015 any_Field12': 'TextEdit', '2015 any_Field13': 'TextEdit', '2015 any_Field14': 'TextEdit', '2015 any_Field15': 'TextEdit', '2015 any_Field16': 'TextEdit', '2015 any_Field17': 'TextEdit', });
lyr_Rennes.set('fieldImages', {'ID_GEOFLA': 'TextEdit', 'CODE_COM': 'TextEdit', 'INSEE_COM': 'TextEdit', 'NOM_COM': 'TextEdit', 'STATUT': 'TextEdit', 'X_CHF_LIEU': 'TextEdit', 'Y_CHF_LIEU': 'TextEdit', 'X_CENTROID': 'TextEdit', 'Y_CENTROID': 'TextEdit', 'Z_MOYEN': 'TextEdit', 'SUPERFICIE': 'TextEdit', 'POPULATION': 'TextEdit', 'CODE_ARR': 'TextEdit', 'CODE_DEPT': 'TextEdit', 'NOM_DEPT': 'TextEdit', 'CODE_REG': 'TextEdit', 'NOM_REG': 'TextEdit', 'MED': 'TextEdit', '2015 any_Field2': 'TextEdit', '2015 any_Field3': 'TextEdit', '2015 any_Field4': 'TextEdit', '2015 any_Field5': 'TextEdit', '2015 any_Field6': 'TextEdit', '2015 any_Field7': 'TextEdit', '2015 any_Field8': 'TextEdit', '2015 any_Field9': 'TextEdit', '2015 any_Field10': 'TextEdit', '2015 any_Field11': 'TextEdit', '2015 any_Field12': 'TextEdit', '2015 any_Field13': 'TextEdit', '2015 any_Field14': 'TextEdit', '2015 any_Field15': 'TextEdit', '2015 any_Field16': 'TextEdit', '2015 any_Field17': 'TextEdit', });
lyr_Polestructurant.set('fieldImages', {'ID_GEOFLA': 'TextEdit', 'CODE_COM': 'TextEdit', 'INSEE_COM': 'TextEdit', 'NOM_COM': 'TextEdit', 'STATUT': 'TextEdit', 'X_CHF_LIEU': 'TextEdit', 'Y_CHF_LIEU': 'TextEdit', 'X_CENTROID': 'TextEdit', 'Y_CENTROID': 'TextEdit', 'Z_MOYEN': 'TextEdit', 'SUPERFICIE': 'TextEdit', 'POPULATION': 'TextEdit', 'CODE_ARR': 'TextEdit', 'CODE_DEPT': 'TextEdit', 'NOM_DEPT': 'TextEdit', 'CODE_REG': 'TextEdit', 'NOM_REG': 'TextEdit', 'MED': 'TextEdit', '2015 any_Field2': 'TextEdit', '2015 any_Field3': 'TextEdit', '2015 any_Field4': 'TextEdit', '2015 any_Field5': 'TextEdit', '2015 any_Field6': 'TextEdit', '2015 any_Field7': 'TextEdit', '2015 any_Field8': 'TextEdit', '2015 any_Field9': 'TextEdit', '2015 any_Field10': 'TextEdit', '2015 any_Field11': 'TextEdit', '2015 any_Field12': 'TextEdit', '2015 any_Field13': 'TextEdit', '2015 any_Field14': 'TextEdit', '2015 any_Field15': 'TextEdit', '2015 any_Field16': 'TextEdit', '2015 any_Field17': 'TextEdit', });
lyr_France.set('fieldLabels', {'code_insee': 'no label', 'nom': 'no label', 'nuts3': 'no label', 'wikipedia': 'no label', 'wikidata': 'no label', 'surf_ha': 'no label', });
lyr_IledeFrance.set('fieldLabels', {'code_insee': 'no label', 'nom': 'no label', 'nuts3': 'no label', 'wikipedia': 'no label', 'wikidata': 'no label', 'surf_ha': 'no label', });
lyr_GrandOuest.set('fieldLabels', {'code_insee': 'no label', 'nom': 'no label', 'nuts3': 'no label', 'wikipedia': 'no label', 'wikidata': 'no label', 'surf_ha': 'no label', });
lyr_AireUrbainedeRennes.set('fieldLabels', {'ID_GEOFLA': 'header label', 'CODE_COM': 'no label', 'INSEE_COM': 'no label', 'NOM_COM': 'no label', 'STATUT': 'no label', 'X_CHF_LIEU': 'no label', 'Y_CHF_LIEU': 'no label', 'X_CENTROID': 'no label', 'Y_CENTROID': 'no label', 'Z_MOYEN': 'no label', 'SUPERFICIE': 'no label', 'POPULATION': 'no label', 'CODE_ARR': 'no label', 'CODE_DEPT': 'no label', 'NOM_DEPT': 'no label', 'CODE_REG': 'no label', 'NOM_REG': 'no label', 'MED': 'no label', 'AU': 'no label', '2015 any_Field2': 'no label', '2015 any_Field3': 'no label', '2015 any_Field4': 'no label', '2015 any_Field5': 'no label', '2015 any_Field6': 'no label', '2015 any_Field7': 'no label', '2015 any_Field8': 'no label', '2015 any_Field9': 'no label', '2015 any_Field10': 'no label', '2015 any_Field11': 'no label', '2015 any_Field12': 'no label', '2015 any_Field13': 'no label', '2015 any_Field14': 'no label', '2015 any_Field15': 'no label', '2015 any_Field16': 'no label', '2015 any_Field17': 'no label', });
lyr_RennesMetropoleEstOuest.set('fieldLabels', {'ID_GEOFLA': 'no label', 'CODE_COM': 'no label', 'INSEE_COM': 'no label', 'NOM_COM': 'no label', 'STATUT': 'no label', 'X_CHF_LIEU': 'no label', 'Y_CHF_LIEU': 'no label', 'X_CENTROID': 'no label', 'Y_CENTROID': 'no label', 'Z_MOYEN': 'no label', 'SUPERFICIE': 'no label', 'POPULATION': 'no label', 'CODE_ARR': 'no label', 'CODE_DEPT': 'no label', 'NOM_DEPT': 'no label', 'CODE_REG': 'no label', 'NOM_REG': 'no label', 'MED': 'no label', '2015 any_Field2': 'no label', '2015 any_Field3': 'no label', '2015 any_Field4': 'no label', '2015 any_Field5': 'no label', '2015 any_Field6': 'no label', '2015 any_Field7': 'no label', '2015 any_Field8': 'no label', '2015 any_Field9': 'no label', '2015 any_Field10': 'no label', '2015 any_Field11': 'no label', '2015 any_Field12': 'no label', '2015 any_Field13': 'no label', '2015 any_Field14': 'no label', '2015 any_Field15': 'no label', '2015 any_Field16': 'no label', '2015 any_Field17': 'no label', });
lyr_RennesMetropoleNordSud.set('fieldLabels', {'ID_GEOFLA': 'no label', 'CODE_COM': 'no label', 'INSEE_COM': 'no label', 'NOM_COM': 'no label', 'STATUT': 'no label', 'X_CHF_LIEU': 'no label', 'Y_CHF_LIEU': 'no label', 'X_CENTROID': 'no label', 'Y_CENTROID': 'no label', 'Z_MOYEN': 'no label', 'SUPERFICIE': 'no label', 'POPULATION': 'no label', 'CODE_ARR': 'no label', 'CODE_DEPT': 'no label', 'NOM_DEPT': 'no label', 'CODE_REG': 'no label', 'NOM_REG': 'no label', 'MED': 'no label', '2015 any_Field2': 'no label', '2015 any_Field3': 'no label', '2015 any_Field4': 'no label', '2015 any_Field5': 'no label', '2015 any_Field6': 'no label', '2015 any_Field7': 'no label', '2015 any_Field8': 'no label', '2015 any_Field9': 'no label', '2015 any_Field10': 'no label', '2015 any_Field11': 'no label', '2015 any_Field12': 'no label', '2015 any_Field13': 'no label', '2015 any_Field14': 'no label', '2015 any_Field15': 'no label', '2015 any_Field16': 'no label', '2015 any_Field17': 'no label', });
lyr_RennesMtropole.set('fieldLabels', {'siren_epci': 'no label', 'nom_epci': 'no label', 'ptot_epci': 'no label', 'surf_km2': 'no label', 'short_name': 'no label', 'wikipedia': 'no label', 'web': 'header label', 'osm_id': 'no label', 'nom_osm': 'no label', 'type_epci': 'no label', '2015 any_Field1': 'no label', '2015 any_Field2': 'no label', '2015 any_Field3': 'no label', '2015 any_Field4': 'no label', '2015 any_Field5': 'no label', '2015 any_Field7': 'no label', '2015 any_Field8': 'no label', '2015 any_Field9': 'no label', '2015 any_Field10': 'no label', '2015 any_Field11': 'no label', '2015 any_Field12': 'no label', '2015 any_Field13': 'no label', '2015 any_Field14': 'no label', '2015 any_Field15': 'no label', '2015 any_Field16': 'no label', '2015 any_Field17': 'no label', });
lyr_CoeurdeMetropole.set('fieldLabels', {'ID_GEOFLA': 'no label', 'CODE_COM': 'no label', 'INSEE_COM': 'no label', 'NOM_COM': 'no label', 'STATUT': 'no label', 'X_CHF_LIEU': 'no label', 'Y_CHF_LIEU': 'no label', 'X_CENTROID': 'no label', 'Y_CENTROID': 'no label', 'Z_MOYEN': 'no label', 'SUPERFICIE': 'no label', 'POPULATION': 'no label', 'CODE_ARR': 'no label', 'CODE_DEPT': 'no label', 'NOM_DEPT': 'no label', 'CODE_REG': 'no label', 'NOM_REG': 'no label', 'MED': 'no label', '2015 any_Field2': 'no label', '2015 any_Field3': 'no label', '2015 any_Field4': 'no label', '2015 any_Field5': 'no label', '2015 any_Field6': 'no label', '2015 any_Field7': 'no label', '2015 any_Field8': 'no label', '2015 any_Field9': 'no label', '2015 any_Field10': 'no label', '2015 any_Field11': 'no label', '2015 any_Field12': 'no label', '2015 any_Field13': 'no label', '2015 any_Field14': 'no label', '2015 any_Field15': 'no label', '2015 any_Field16': 'no label', '2015 any_Field17': 'no label', });
lyr_Coeur1.set('fieldLabels', {'ID_GEOFLA': 'no label', 'CODE_COM': 'no label', 'INSEE_COM': 'no label', 'NOM_COM': 'no label', 'STATUT': 'no label', 'X_CHF_LIEU': 'no label', 'Y_CHF_LIEU': 'no label', 'X_CENTROID': 'no label', 'Y_CENTROID': 'no label', 'Z_MOYEN': 'no label', 'SUPERFICIE': 'no label', 'POPULATION': 'no label', 'CODE_ARR': 'no label', 'CODE_DEPT': 'no label', 'NOM_DEPT': 'no label', 'CODE_REG': 'no label', 'NOM_REG': 'no label', 'MED': 'no label', '2015 any_Field2': 'no label', '2015 any_Field3': 'no label', '2015 any_Field4': 'no label', '2015 any_Field5': 'no label', '2015 any_Field6': 'no label', '2015 any_Field7': 'no label', '2015 any_Field8': 'no label', '2015 any_Field9': 'no label', '2015 any_Field10': 'no label', '2015 any_Field11': 'no label', '2015 any_Field12': 'no label', '2015 any_Field13': 'no label', '2015 any_Field14': 'no label', '2015 any_Field15': 'no label', '2015 any_Field16': 'no label', '2015 any_Field17': 'no label', });
lyr_Coeur2.set('fieldLabels', {'ID_GEOFLA': 'no label', 'CODE_COM': 'no label', 'INSEE_COM': 'no label', 'NOM_COM': 'no label', 'STATUT': 'no label', 'X_CHF_LIEU': 'no label', 'Y_CHF_LIEU': 'no label', 'X_CENTROID': 'no label', 'Y_CENTROID': 'no label', 'Z_MOYEN': 'no label', 'SUPERFICIE': 'no label', 'POPULATION': 'no label', 'CODE_ARR': 'no label', 'CODE_DEPT': 'no label', 'NOM_DEPT': 'no label', 'CODE_REG': 'no label', 'NOM_REG': 'no label', 'MED': 'no label', '2015 any_Field2': 'no label', '2015 any_Field3': 'no label', '2015 any_Field4': 'no label', '2015 any_Field5': 'no label', '2015 any_Field6': 'no label', '2015 any_Field7': 'no label', '2015 any_Field8': 'no label', '2015 any_Field9': 'no label', '2015 any_Field10': 'no label', '2015 any_Field11': 'no label', '2015 any_Field12': 'no label', '2015 any_Field13': 'no label', '2015 any_Field14': 'no label', '2015 any_Field15': 'no label', '2015 any_Field16': 'no label', '2015 any_Field17': 'no label', });
lyr_Rennes.set('fieldLabels', {'ID_GEOFLA': 'no label', 'CODE_COM': 'no label', 'INSEE_COM': 'no label', 'NOM_COM': 'no label', 'STATUT': 'no label', 'X_CHF_LIEU': 'no label', 'Y_CHF_LIEU': 'no label', 'X_CENTROID': 'no label', 'Y_CENTROID': 'no label', 'Z_MOYEN': 'no label', 'SUPERFICIE': 'no label', 'POPULATION': 'no label', 'CODE_ARR': 'no label', 'CODE_DEPT': 'no label', 'NOM_DEPT': 'no label', 'CODE_REG': 'no label', 'NOM_REG': 'no label', 'MED': 'no label', '2015 any_Field2': 'no label', '2015 any_Field3': 'no label', '2015 any_Field4': 'no label', '2015 any_Field5': 'no label', '2015 any_Field6': 'no label', '2015 any_Field7': 'no label', '2015 any_Field8': 'no label', '2015 any_Field9': 'no label', '2015 any_Field10': 'no label', '2015 any_Field11': 'no label', '2015 any_Field12': 'no label', '2015 any_Field13': 'no label', '2015 any_Field14': 'no label', '2015 any_Field15': 'no label', '2015 any_Field16': 'no label', '2015 any_Field17': 'no label', });
lyr_Polestructurant.set('fieldLabels', {'ID_GEOFLA': 'no label', 'CODE_COM': 'no label', 'INSEE_COM': 'no label', 'NOM_COM': 'no label', 'STATUT': 'no label', 'X_CHF_LIEU': 'no label', 'Y_CHF_LIEU': 'no label', 'X_CENTROID': 'no label', 'Y_CENTROID': 'no label', 'Z_MOYEN': 'no label', 'SUPERFICIE': 'no label', 'POPULATION': 'no label', 'CODE_ARR': 'no label', 'CODE_DEPT': 'no label', 'NOM_DEPT': 'no label', 'CODE_REG': 'no label', 'NOM_REG': 'no label', 'MED': 'no label', '2015 any_Field2': 'no label', '2015 any_Field3': 'no label', '2015 any_Field4': 'no label', '2015 any_Field5': 'no label', '2015 any_Field6': 'no label', '2015 any_Field7': 'no label', '2015 any_Field8': 'no label', '2015 any_Field9': 'no label', '2015 any_Field10': 'no label', '2015 any_Field11': 'no label', '2015 any_Field12': 'no label', '2015 any_Field13': 'no label', '2015 any_Field14': 'no label', '2015 any_Field15': 'no label', '2015 any_Field16': 'no label', '2015 any_Field17': 'no label', });
lyr_Polestructurant.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});